### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Yoanndp**
Fixed typos in README file for improved clarity and readability.

### CODE REVIEW

**Comment by Yoanndp** [comment]
@seamusdemora hello, any feedback on this?

**Comment by seamusdemora** [comment]
@Yoanndp : 

I'm sorry about that - I completely failed to notice the PR. Honestly, your changes look OK to me, but I've apparently revised the README file since you submitted the PR originally, so there are some conflicts that need to be resolved before the PR can be merged. How would you suggest we handle this?

**Comment by Yoanndp** [comment]
No worries, let me resolve the conflict

**Comment by seamusdemora** [comment]
Will do!  Please make a comment here when you've finished - I seem to keep up with those :P

**Comment by Yoanndp** [comment]
@seamusdemora Hello, the conflicts are resolved. Please let me know if it is good for you.

**Pull request merged**
